name: sacco
description: Pure Dart library allowing you to easily create an HD Wallet and create, sign and send Cosmos-SDK transactions.
version: 0.1.5
homepage: https://github.com/commercionetwork/sacco.dart

environment:
  sdk: ">=2.12.0-0 <3.0.0"

dependencies:
  bech32: ">=0.2.0 <0.3.0"
  convert: ">=2.0.0 <4.0.0"
  equatable: ">=2.0.0 <3.0.0"
  http: ">=0.13.0 <0.14.0"
  pointycastle: ^3.0.0-nullsafety.2

dev_dependencies:
  test: ">=1.16.0 <2.0.0"
